# Default or base configuration for SE(3) diffusion experiments.

defaults:
  - train_StateFold

data:
  dynamics: True
  frame_time: 5
  frame_sample_step: 1
  max_protein_num: 6
  csv_path: train_merged_all.csv
  test_csv_path:  test_merged_all.csv


eval:
  name: StateFold_Temporal_${model.ipa.temporal}_eval
  gpu_id: null
  repeat_time: 1
  random_sample: False
  mode: 0 # 0 for single step 1: for extrapolation 2: for batch eval
  extrapolation_time: 10

  # Path to model weights.
  weights_path: ./weights/paper_weights.pth
  output_dir: ${experiment.base_root}/evaluation_outputs/
  eval_batch_size: 1

experiment:
    use_ddp: False
    training: False

model:
  ipa:
    temporal: True

hydra:
  run:
    dir: ${experiment.base_root}/eval_out_logs/${experiment.name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
